# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lesson20_ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lesson20_ChatApp

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'SDWebImage', '~> 5.0'
pod 'MessageKit', '~> 3.1.0'


end
